version: "2.1"

services:
  central:
    image: udupay
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 3050:3050
      - 9229:9229
    command: node --inspect=0.0.0.0:9229 bin/www
